blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/",
         views.post_detail, name="post_detail"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    # path("search/", views.post_search, name="post_search"),

    # tag
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),

    path("feed/", LatestPostsFeed(), name="post_feed")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish',]

    def __str__(self):
        return self.title

    objects = models.Manager()  # The defult manager
    published = PublishedManager()  # Our custom manager

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])


class Comments(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField( auto_now=False, auto_now_add=True)
    updated = models.DateTimeField( auto_now=True, auto_now_add=False)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created',]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from .models import Comments


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, required=True)
    email = forms.EmailField(required=True)
    to = forms.EmailField(required=True)
    comments = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    """CommentForm definition."""

    class Meta:
        model = Comments
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Count

from django.contrib.postgres.search import SearchVector
from taggit.models import Tag

from .models import Post, Comments
from .forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    tag = None

    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            posts = Post.published.annotate(
                search=SearchVector('title', 'body'),
            ).filter(search=query)

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/post/list.html',
                  {'posts': posts, 'page_obj': page_obj, 'tag': tag, 'query': query, })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments,
                   'new_comment': new_comment, 'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    send = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [cd['to']],
            )
            send = True

    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'send': send})


# def post_search(request):
#     form = SearchForm()
#     query = None
#     results = []

#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Post.published.annotate(
#                 search=SearchVector('title', 'body'),
#             ).filter(search=query)

#     return render(request, 'blog/post/list.html',
#                   {
#                       'form': form,
#                       'query': query,
#                       'results': results,
#                   })

blog/templates/blog/base.html
{% load blog_tags %}
{% load blog_filters %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
</head>

<body>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/fontawesome-all.min.js' %}"></script>

    <header>
        {% include 'blog/nav.html' %}
    </header>

    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>

    <div id="sidebar">
        <p class="card card-header" style="margin: 15px;width: 20rem;">This is my blog. I've written {% total_posts %} posts so far.</p>
    
        
        {% show_latest_posts 3 %}

        
        {% get_most_commented_posts as most_commented_posts %}
        <div class="card" style=" margin:15px;width: 20rem;">
            <div class="card-header">
                Most comment posts
            </div>
            <ul class="list-group list-group-flush">
                {% for post in most_commented_posts %}
                    <li class="list-group-item">
                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</body>

</html>

blog/templates/blog/nav.html
<nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:post_list' %}"><i class="fa-solid fa-blog"></i> Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:post_feed' %}">RSS</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form method="get" class="d-flex" role="search">
                        <input id="id_query" name="query" required class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

blog/templates/blog/pagination.html
<div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        
    </div>

{% comment %} <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    
    {% for page_number in page_obj.paginator.page_range %}
        <li class="page-item">
            <a class="page-link" 
            {% comment %} href="{% url 'terms-by-page' page_number %}" 

            class="{% if page_number == page_obj.number %}current{% endif %}"
            >
                {{page_number}}
            </a>
        </li>
    {% endfor %}
        

    
    {% comment %} <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li> 


    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav> {% endcomment %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load blog_filters %}



{% block title %}
    {{post.title}}
{% endblock title %}
    

{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{ post.body|markdown|safe  }}

    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>


    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{forloop.counter}} by {{comment.name}}
                {{comment.created}}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="" method="post">
            {{comment_form.as_p}}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
        
        
{% endblock content %}
    

blog/templates/blog/post/latest_posts.html
{% comment %} <ul>
    {% for post in latest_post %}
        <li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
    {% endfor %}
</ul> {% endcomment %}
<div class="card" style=" margin:15px; width: 20rem;">
            <div class="card-header">
                Latest posts
            </div>
            <ul class="list-group list-group-flush">
                {% for post in latest_post %}
                    <li class="list-group-item">
                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load blog_filters %}

{% block title %}
    My Blog
{% endblock title %}

{% block content %}
    
    {% if tag %}
        <h2>Posts tagged with "{{tag.name}}"</h2>
    {% endif %}

    
    {% if query %}
        
        {% include 'blog/post/search.html' with results=posts %}
        
    {% else %}    
    {% for post in posts %}
        {% include 'blog/post/post_card.html' with post=post %}
        
    {% endfor %}

    {% include 'blog/pagination.html' with page=posts %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post/post_card.html
{% load blog_tags %}
{% load blog_filters %}

<div class="card" style="margin: 15px;">
        <a href="{{ post.get_absolute_url }}" style="text-decoration: none;">
        <h3 class=" card-header">{{ post.title }}</h3>
        <div class="card-body">
            </a>
            <h6 class="card-subtitle mb-2 text-muted">Published {{post.publish}} by {{post.author}}</h6>
            <p class="tags"> Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %},{% endif %}    
            {% endfor %}
        </p> 
            <p class="card-text">{{post.body|markdown|safe|truncatewords:30}}</p>
            <a href="{% url 'blog:post_share' post.id %}" class="btn btn-primary card-link">share</a>
            <a href="#" class="btn btn-primary card-link">Another link</a>
        </div>
    </div>

blog/templates/blog/post/search.html
{% load blog_tags %}
{% load blog_filters %}


{% block content %}
    
      <h1>Post containing "{{ query }}"</h1>
      <h3>
        
        {% comment %} {% with results.count as total_results %}
            Found {{ total_results }} result{{total_results|pluralize}}
        {% endwith %} {% endcomment %}
            
      </h3>
      
      {% for post in results %}
        {% include 'blog/post/post_card.html' with post=post %}

        {%empty%}
            <p>There are no results for your query.</p>
      {% endfor %}
      
    
        
    
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
Share a post
{% endblock title %}


{% block content %}

    {% if send %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{form.cleaned_data.to}}
        </p>

    {% else %}
        <h1>Share "{{post.title}}" by e-mail</h1>
        <form action="" method="post">
            <!-- {{form.as_p}} -->
            
            {% for field in form %}
                <div>
                    {{field.label_tag}}  {{field}}
                    {{field.errors}}
                </div>
            {% endfor %}
                
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock content %}